spring:
  datasource:
    url: jdbc:postgresql://iden-it.cfu7vp0r2pen.ap-northeast-2.rds.amazonaws.com:5432/dev
    driver-class-name: org.postgresql.Driver
    username: idenit
    password: chlgytjr0421!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
