spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dmz-dev.c9auakg60tyy.ap-northeast-2.rds.amazonaws.com/dmz-dev?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ENC(3kDqYdZRxEqch9kNGZZssA==)
    password: ENC(KkY/KGNoPZOvqKVNSN2gcMGnf8mMLbzI)

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

