spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:dmz-local
    driverClassName: org.h2.Driver
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

